### ISSUE TITLE
Wrong message for key word searching filtered by two or more  Pet type

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#10]
# Description

Searching by  entering key word and  selecting User`s town and Pet type  filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter nQQb
3. Select fish and cat for pet type 
4. Press Search option
# Expected result

A window with "you have successfully searched by:
"nQQb " fish cat
# Actual result

"You have successfully searched by:  fish cat"
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
