### ISSUE TITLE
Wrong message for key word searching filtered by Subscription

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#11]
# Description

Searching by  entering keyword and  selecting User`s town and Subscription filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter nQQb
3. Select News about promotions and Notification for vaccination for subscription 
4. Press Search option
# Expected result

A window with "you have successfully searched by:
"nQQb "  User's Townn News about promotions and Notification for vaccination
# Actual result

Message "You have successfully searched by:User's town News about promotions and Notification for vaccination " is displayed 
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
