### ISSUE TITLE
Wrong message for key word searching filtered by User`s town , Pet type and subscription

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#12]
# Description

Searching by  entering keyword and  selecting User`s town , Subscription and Pet type  filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter "Kucho "
3. Select Check User's Town checkbox
4. Select Check option from Pet type
5. Select Notification for vaccination for subscription
6. Press Search option
# Expected result

A window with "you have successfully searched by:
"Kucho " User`s town Notification for vaccinationand Pet type
# Actual result

"You have successfully searched by:User's Town  Pet Type Notification for vaccination" message is dislayed 
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forevr
