### ISSUE TITLE
Wrong message for key word searching filtered by Pet breed , Pet type and subscription

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#13]
# Description

Searching by  entering key word and  selecting User`s town and Subscription filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter "Cat lover "
3. Select  Pet Breed checkbox
4. Select Dog form pet type
5. Select  Notification for vaccination for subscription
6. Press Search option, 
# Expected result

A window with "you have successfully searched by:
"Cat lover" Pet Breed, Dog and Notification for vaccination
# Actual result

"You have successfully searched by:Dog, Pet Breed ,Notification for vaccination" message is displayed
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forevr
