### ISSUE TITLE
Incorect message for searching by key word ,Pet birthdate,Pet type and subscription

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#14]
# Description

Searching by  entering keyword and  selecting Pet birthdate,Pet type and subscription filters ,displays wrong message 
# Steps
1. Navigate to Search page
   2 .In search field enter "Pumeranian"
2. Select Check Pet Birthday checkbox
3. Select Check option from Cat
4. Select Check option Notification for vaccination
5. Press Search option
# Expected result

A window with "you have successfully searched by:
"Pumeranian " PetBirth day  Notification for vaccination and Cat
# Actual result

"You have successfully searched by: PetBirth day  Notification for vaccination and Cat"message  is displayed
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forevr
