### ISSUE TITLE
Empty pet breed when fish is selected for pet type

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#15]
# Description

Checking if the Pet type drop down displays the right breeds for the chosen pet type: empty breed for Fish pet type
# Steps
1. Click on the dropdown menu  "Pet type" 
2. Select "Fish"
3. Click on the "Pet breed" drop down 
4. Click on the last option: empty row
# Expected result

A breed is shown in the " Pet breed" field for Fish, selected as Pet type
# Actual result

An empty row is shown as a breed in the " Pet breed" field for Fish, selected as Pet type
# Environment

Mozila firefox 38.0.5

**Comment by MartinGyurov** [comment]
fixed

**Comment by linaNikolova** [comment]
# Retested: fixed
