### ISSUE TITLE
Incorrect message when searching  by keyword and all filter options selected

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#17]
# Description

Searching by  entering keyword and  selecting User`s town and Pet breed filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter "Fluffy"
3. Select all options
4. Press Search option
# Expected result

A window with "you have successfully searched by:
"Fluffy " User's Town,Pet Owner's name,Pet Breed,Pet Birthday,Cat,Dog,Reptile,Fish,Insect,Rodent,Other,News about promotions,Notification for vaccination,News about special offers"
# Actual result

"You have successfully searched by: User's Town,Pet Owner's name,Pet Breed,Pet Birthday,Cat,Dog,Reptile,Fish,Insect,Rodent,Other,News about promotions,Notification for vaccination,News about special offers" message is displayed
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
