### ISSUE TITLE
Pet Owner's name field accepts special characters

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#19]
# Description

You can successfully register user entering special characters in the "Pet Owner" field.
# Steps
1. Enter gosho for  "Pet name"  
2. Select Dog from "Pet type"
3. Select Akita from"Pet breed"
4. Select female as "Pet gender"
5. Enter **N00B#ggEasyLamer** for "Pet Owner"
6. Choose birthdate
7. Select Black from "Color"
8. Click the "Submit" button 
# Expected result

The system indicates an error as the special character is an invalid value for the "Pet Owner" field
# Actual result

The system indicates success as the data is accepted.
# Environment

Mozila firefox 38.0.5

**Comment by MartinGyurov** [comment]
fixed

**Comment by linaNikolova** [comment]
# Fixed & Retested
