### ISSUE TITLE
User Reg - Capital letter in User name

### ISSUE THREAD

**Issue by MartinGyurov** [rosko89/PetStoreTestingTask#21]
# Description

User name field should accept all kinds of symbols except special ones
# Steps
1. Navigate to User Registration page
2. In User name enter Tsveti15
3. Fill out the rest of the fields with valid data
4. Click Submit
# Expected result

To be able to register new user Tsveti15
# Actual result

You get a message on user name: "Please match the requested format"

**Comment by mzhingova** [comment]
# Fixed

**Comment by MartinGyurov** [comment]
### Retested - Pass
