### ISSUE TITLE
User Reg - Wrong display of Birthday

### ISSUE THREAD

**Issue by MartinGyurov** [rosko89/PetStoreTestingTask#23]
# Description
# Steps
1. Navigate to User Registration page
2. Click on Birthday and pick a day from the calendar (for example day:20 month and year default )
# Expected Result

The displayed Birthday should be 06/20/1940
# Actual Result

The displayed Birthday is 06/20/2015

**Comment by mzhingova** [comment]
# Fixed

**Comment by MartinGyurov** [comment]
### Retested - Pass
