### ISSUE TITLE
User Reg - No Email validation

### ISSUE THREAD

**Issue by MartinGyurov** [rosko89/PetStoreTestingTask#24]
# Description

You can type any kind of Email and as long as you have @ and at least 1 letter and/or number the email is shown as valid
# Steps
1. Navigate to User Registration page
2. In Email enter blqblq@blq123
# Expected Result

Error message: " "
# Actual Result

The Email is accepted as valid

**Comment by mzhingova** [comment]
# Fixed #

**Comment by MartinGyurov** [comment]
### Retested - Pass
