### ISSUE TITLE
Inconsistency in the UI

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#25]
# Description

The "Pet registration" page does not follow  the UI
# Step

1.Ope the "home page"
2.Go to the navigation  bar
3. Click on the "Search page"
4.Click on the "Pet registration page"
5.Click on the "User registration page " 
# Expected Results

The navigation bar should follow the frame of the form 
example:
![not bugy](https://cloud.githubusercontent.com/assets/7475051/8325957/25459e3a-1a66-11e5-950d-f08d114a41a7.png)
# Actual Result

![bugy](https://cloud.githubusercontent.com/assets/7475051/8325963/2bcf6a4c-1a66-11e5-8b86-d5c4d17d3dbf.png)

**Comment by MartinGyurov** [comment]
fixed

**Comment by MartinGyurov** [comment]
fixed

**Comment by linaNikolova** [comment]
# Retested: fixed!
