### ISSUE TITLE
User is allowed to write digits in the Birth date field in Pet registration form

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#26]
# Description

Birth date field in Pet registration allows user to write digits in it and takes them for correct data
# Steps
1. Click  "Birth date " field
2. Enter '864' in the field without using the calender 
# Expected result

Indication for a mistake or an error message for incorrect input
# Actual result

Green thumb up is shown and if valid data is entered in all other required fields and the Submit button/ Enter is pressed, no error message is displayed 
![bugbirthday field](https://cloud.githubusercontent.com/assets/9518533/8327891/98b494e4-1a74-11e5-8853-76d3a8a4312c.PNG)

**Comment by MartinGyurov** [comment]
Fixed thanks to mzhingova

**Comment by linaNikolova** [comment]
# Retested: fixed
