### ISSUE TITLE
Digits in the birth day field in the Pet Registration form

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#27]
# Description

Birth date field in Pet registration form allows user to write digits in it and when "Enter" is pressed, replaces them with present-day
# Steps
1. Open the form
2. Do not enter any data in the fields
3. Click "Birth date" field
4. Enter '474' in the field without using the calender
5. Press "Enter"
# Expected result

Indication for a mistake or an error message for incorrect input
# Actual result

Green thumb up is shown 
![bugbirthday field_2](https://cloud.githubusercontent.com/assets/9518533/8327390/a140bea2-1a70-11e5-8ee3-07b8bad5edf9.PNG)
when "Enter" is pressed '474' is replaced with todays date
![bugbirthday field_2_2](https://cloud.githubusercontent.com/assets/9518533/8327392/a53d849a-1a70-11e5-8120-c69231c4027c.PNG)

**Comment by MartinGyurov** [comment]
Fixed thanks to mzhingova

**Comment by linaNikolova** [comment]
# Retested: fixed
