### ISSUE TITLE
Calendar for birth date in Pet registration form does not appear

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#28]
# Description

The calender does not appear when digits are entered manually in the birth day field in the Pet registration form,'enter' is pressed,  than the date generated is erased, than the field is selected again
# Steps
1. Open the Pet registration form
2. Do not enter any data in the fields
3. Click "Birth date" field
4. Enter '4778964' in the field without using the calender
5. Click 'Enter"
6. Delete the input with 'backspace'
7. Click on the Birthdate field again
# Expected result

The calender is shown for the user to choose date
# Actual result

When "Enter is clicked 4778964 is replaced by the present date, than when erased and the field is clicked again it shows a list of all dates or other data ever entered in this field 
![nocallenderbug](https://cloud.githubusercontent.com/assets/9518533/8327365/661673b2-1a70-11e5-9142-4a0b20098d20.png)

**Comment by MartinGyurov** [comment]
Fixed thanks to mzhingova

**Comment by linaNikolova** [comment]
# Retested:fixed
