### ISSUE TITLE
User can edit the date in birth date field in Pet Registration form and it is still correct

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#29]
# Description

When a date is chosen from the calender it can be manually edited into incorrect date and the field indicates it as correct
# Steps
1. Open the Pet registration form
2. Do not enter any data in the fields
3. Click "Birth date" field
4. Pick 07/14/2015 as a date
5. Edit the fields adding random numbers in it
# Expected result

Error message or system indication for wrong input
# Actual result

The system indicates correct data and a green thumb up is shown
![bugbday](https://cloud.githubusercontent.com/assets/9518533/8327777/b2961014-1a73-11e5-9eb2-880122805cb4.PNG)

**Comment by MartinGyurov** [comment]
Fixed thanks to mzhingova

**Comment by linaNikolova** [comment]
# Retested: fixed
