### ISSUE TITLE
Wrong message

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#3]
# Description

The alert box displays wrong message.
# Steps
1. Navigate to Search page 
2. Press Search button
# Expected result

 A window with "you have successfully searched"
# Actual result

Alert message -"You have successfully searched by:"
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed foreve
