### ISSUE TITLE
User Reg - Different confirm pass

### ISSUE THREAD

**Issue by MartinGyurov** [rosko89/PetStoreTestingTask#30]
# Description

You can enter a completely different password as a confirm password, as long as it matches the criteria for valid password the field accepts it as a valid one
# Steps
1. Navigate to User Registration page
2. Enter Valid Password :11!!QQqq
3. Enter Valid Confirm password but different from the one in Password field: "11!!QQqq@@
# Expected Result

Red thumb down is shown in the confirm password field.
# Actual Result

Confirm password field accept the password you have entered although its different from field Password

**Comment by mzhingova** [comment]
# Fixed

**Comment by MartinGyurov** [comment]
### Retested - Pass
