### ISSUE TITLE
When Pet registration page is refreshed the information reappears

### ISSUE THREAD

**Issue by linaNikolova** [rosko89/PetStoreTestingTask#31]
# Description

When the Pet registration page is refreshed it does not clear all the fields only "Pet Breed" is returned to "Please choose from above" which is the default value when no Pet type is chosen
# Steps
1. Open the Pet registration form
2. Enter data i all fields
3. Click refresh button 
# Expected result

All fields are empty after the refresh 
# Actual result

The entered data remains in all fields, only the Pet Breed is reset and shows "Please choose from above" which is the default value when no Pet type is chosen, but the Pet type field remains filled in so it technically doesn't behave adequate even for the data that remains filled in.
![norefresh](https://cloud.githubusercontent.com/assets/9518533/8328651/3afebbd4-1a7b-11e5-82ad-286496ad029e.png)

**Comment by MartinGyurov** [comment]
Fixed

**Comment by linaNikolova** [comment]
The Pet gender checkbox still remains with its previously chosen value...

**Comment by linaNikolova** [comment]
# Retested: fixed
