### ISSUE TITLE
User Reg - User can edit the date in birth date field and it is still correct

### ISSUE THREAD

**Issue by MartinGyurov** [rosko89/PetStoreTestingTask#32]
# Description

When a date is chosen from the calender it can be manually edited into incorrect date and the field indicates it as correct
# Steps
1. Open the User Registration form
2. Do not enter any data in the fields
3. Click "Birth date" field
4. Pick 05/10/2000 as a date
5. Edit the fields adding random numbers in it
# Expected result

Error message or system indication for wrong input
# Actual result

The system indicates correct data and a green thumb up is shown
![1](https://cloud.githubusercontent.com/assets/12813699/8328818/b56fa418-1a7c-11e5-9e81-08c4fc100de8.png)

**Comment by mzhingova** [comment]
# FIXED

**Comment by MartinGyurov** [comment]
## Retested - Pass
