### ISSUE TITLE
User Reg - Birth date field

### ISSUE THREAD

**Issue by MartinGyurov** [rosko89/PetStoreTestingTask#33]
# Description

When u click on Birth date and type any number its accepted as a valid value
# Steps
1. Navigate to User Registration page
2. Click on Birth date field and type: "1"
# Expected Result

Error message or system indication for wrong input
# Actual Result

The system indicates correct data and a green thumb up is shown
![12](https://cloud.githubusercontent.com/assets/12813699/8329166/ec75b0d0-1a7f-11e5-9921-145bb3ef128a.png)

**Comment by mzhingova** [comment]
# FIXED

**Comment by MartinGyurov** [comment]
## Retested - Pass

**Comment by jakimcho** [comment]
Passed? Raly? :) How did you retest it.
