### ISSUE TITLE
Wrong message for key word searching 

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#4]
# Description

Searching by key word  display wrong result 
# Steps
1. Navigate to Search page
2. In search field enter "BUBU
3. Press Search option
# Expected result

A window with "you have successfully searched by:
" BUBU"
# Actual result

Alert box containing "you have successfully searched by:"  message 
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
