### ISSUE TITLE
Search by  key word and user`s town filter selectet ,displays wrong message 

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#5]
# Description

Searching by  entering keyword and  selecting User`s town filter ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter "KUKU"
3. Select  "User's Town" checkbox
4. Press Search option
# Expected result

A window with "you have successfully searched by:
"KUKU " User's Town
# Actual result

"You have successfully searched by: User's Town" message is displayed 
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
