### ISSUE TITLE
Searching by key word and Pet breed displays wrong result 

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#6]
# Description

Searching by  entering keyword and  selecting Pet breed  filter ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter "KUKU"
3. Select  "Pet breed" checkbox
4. Press Search option
# Expected result

A window with "you have successfully searched by:
"KUKU " Pet breed 
# Actual result

"You have successfully searched by:Pet breed" is displayed
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
