### ISSUE TITLE
Searching by key word and Birthdate displays wrong result

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#7]
# Description

Searching by  entering keyword and  selecting Birthdate filter ,displays wrong message 
# Steps
1. Navigate to Search page
   2.In search field enter "KUKU"
   3.Select  "Birth date" checkbox
   4.Press Search option
# Expected result

A window with "you have successfully searched by:
"KUKU " Birthdate 
# Actual result

Alert box containing  the following message "You have successfully searched by: Birth date " is displayed
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

въпреки че няма поле Birthdate, а само Pet Birthday :Р Но предполагам то е търсеното ;)

**Comment by mzhingova** [comment]
Fixed forever
