### ISSUE TITLE
Searching by key word and User`s Town and Pet breed filters, displays wrong result

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#8]
# Description

Searching by  entering keyword and  selecting User`s town and Pet breed filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter nQQb
3. Select  "User's Town" checkbox
4. Select "Pet Breed" checkbox
5. Press Search option
# Expected result

A window with "you have successfully searched by:
"nQQb " Pet Breed User's Town
# Actual result

Alert box containing  the following message "You have successfully searched by:User's Town  Pet Breed" is dislayed 
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
