### ISSUE TITLE
Wrong message for key word searching filtered by User`s town and Pet birthday 

### ISSUE THREAD

**Issue by mzhingova** [rosko89/PetStoreTestingTask#9]
# Description

Searching by  entering keyword and  selecting User`s town and Pet birthday  filters ,displays wrong message 
# Steps
1. Navigate to Search page
2. In search field enter nQQb
3. Select  "User's Town" checkbox
4. Select "Pet Birthday" checkbox
5. Press Search option
# Expected result

A window with "you have successfully searched by:
"nQQb " Pet Breed Pet birthday
# Actual result

"You have successfully searched by:User's Town  Pet Birthday" message is dislayed 
# Environment

Mozila firefox 38.0.5

**Comment by linaNikolova** [comment]
# Fixed

**Comment by mzhingova** [comment]
Fixed forever
